# NAME: Konner Macias,Cavan Stewart
# EMAIL: konnermacias@g.ucla.edu,cavanwstewart@gmail.com
# ID: 004603916,304654853

default:
	cp lab3b.py lab3b
	chmod +x lab3b
dist:
	tar -czf lab3b-004603916.tar.gz lab3b.py Makefile README

clean:
	rm -f lab3b-004603916.tar.gz
