# NAME: Konner Macias,Cavan Stewart
# EMAIL: konnermacias@g.ucla.edu,cavanwstewart@gmail.com
# ID: 004603916,304654853

default: build

build:
	gcc -Wall -Wextra -o lab3a lab3a.c

dist:
	tar -czf lab3a-004603916.tar.gz lab3a.c Makefile README ext2_fs.h

clean:
	rm -f lab3a lab3a-004603916.tar.gz